apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: market-gr-services

images:
- name: government-gr-image
  newName: crprodwesteurope.azurecr.io/fiskaltrust/gr/government

resources:
- serviceaccount.yml
- ingress.yml
- configmap.yml
- secret.yml
- ../../base
