apiVersion: v1
kind: Secret
metadata:
  name: secret-appsettings-government-gr
type: Opaque
stringData:
  AzureAd__TenantId: ""
  AzureAd__ClientId: ""
  AzureAd__Audience: ""
  MyData__AadeUserId: ""
  MyData__SubscriptionKey: ""
