apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 2ffe3d43-921a-4488-8575-8edd3985dce7
  namespace: market-gr-services
  labels:
    azure.workload.identity/use: "true"
  name: government-gr-sa
