apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: TODO
  namespace: market-gr-services
  labels:
    azure.workload.identity/use: "true"
  name: government-gr-sa
