apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 9d92feb4-0d43-4d3b-b0ed-26267676e28b
  namespace: market-gr-services
  labels:
    azure.workload.identity/use: "true"
  name: government-gr-sa
